# Generated by Django 5.2.9 on 2026-03-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField(choices=[('Adidas', 'Adidas'), ('Apple', 'Apple'), ('Boat', 'Boat'), ('Dell', 'Dell'), ('HP', 'HP'), ('IG', 'IG'), ('Nike', 'Nike'), ('Philips', 'Philips'), ('Prestige', 'Prestige'), ('Puma', 'Puma'), ('Redmi', 'Redmi'), ('Reebok', 'Reebok'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Whirlpool', 'Whirlpool')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='filemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.TextField(max_length=100)),
                ('seller_rating', models.FloatField()),
                ('seller_city', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.TextField(max_length=100)),
                ('product_units_sold', models.IntegerField()),
                ('product_warranty', models.IntegerField()),
                ('product_return_days', models.IntegerField()),
                ('product_is_returnable', models.BooleanField()),
                ('product_score', models.FloatField()),
                ('product_rating', models.FloatField()),
                ('product_stock_available', models.IntegerField()),
                ('product_color', models.TextField(max_length=100)),
                ('product_discount', models.FloatField()),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_dash_app.brand')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_dash_app.seller')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_delivery_date', models.IntegerField()),
                ('order_final_price', models.FloatField()),
                ('order_payemnt_method', models.TextField(choices=[('CARD,Wallet', 'CARD,Wallet'), ('COD,CARD', 'COD,CARD'), ('COD,UPI,CARD', 'COD,UPI,CARD'), ('UPI,CARD', 'UPI,CARD')], max_length=100)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_dash_app.product')),
            ],
        ),
    ]
